### PR TITLE
corrected setup instructions

### PR DESCRIPTION
**Pull request by am-kaiser**
There have been issues without setting up the atmodat checker. In this branch they are removed.

### CODE REVIEW

**Comment by jkretz** [comment]
I am fine with that and you can merge at any. Should we maybe remove the comment instruction above the changed line?

**Comment by am-kaiser** [comment]
> 
> 
> I am fine with that and you can merge at any. Should we maybe remove the comment instruction above the changed line?

Do you mean this part: (only necessary for developers) ?

**Comment by jkretz** [comment]
> Do you mean this part: (only necessary for developers) ?

Yes. But I would also be okay to leave it in

**Comment by am-kaiser** [comment]
> 
> 
> > Do you mean this part: (only necessary for developers) ?
> 
> Yes. But I would also be okay to leave it in

I would leave it on for the moment to make it clear that it is only for development purposes. But we should consider to leave the whole line out for the final revised version of the checker.

**Pull request merged**
