### PR TITLE
added super linter action

### PR DESCRIPTION
**Pull request by am-kaiser**
This branch adds the super linter action. 

"The super-linter finds issues and reports them to the console output. Fixes are suggested in the console output but not automatically fixed, and a status check will show up as failed on the pull request." (https://github.com/github/super-linter)

The linter will be run on pushes and pull request to the master branch.

### CODE REVIEW

**Comment by jkretz** [comment]
Sounds like a nice addition to me. Should the linter.yml be in .github/workflows according to the docs?

**Comment by am-kaiser** [comment]
> 
> 
> Sounds like a nice addition to me. Should the linter.yml be in .github/workflows according to the docs?

yes you are right. I will change that

**Comment by jkretz** [comment]
Which of the 3 pythons linters should we use? flake8 looks best for me

**Comment by am-kaiser** [comment]
> 
> 
> Which of the 3 pythons linters should we use? flake8 looks best for me

sounds good

**Comment by am-kaiser** [comment]
@jkretz do you know how to solve the errors from the linter output? Otherwise I would be fine with merging it like this into the master branch

**Comment by jkretz** [comment]
[atmodat_checker/atmodat_checklib/register/__init__.py:9:1: F401 'inspect' imported but unused 
This can be avoid be removing this line
The F401/F403 errors can not be easily resolved in the cod. An idea would be to ignore those errors in flake8. This can be done with the --ignore attribute. This can be set via the .flake8 file according to the super-linter docu. One can set the path to that file in the linter.yml but I don't know yet where to put this file.

**Comment by jkretz** [comment]
Ignoring the errors F401 and F403 regarding the "import *" related issues is working now. As this overrides the default .flake from super-linter, a line length error is present now. According to PEP8, the max line length should be 79, but we could set this to a higher value. Looking at compliance-check-lib and cc-yaml, they also seem to allow for longer lines. 
I would propose 119 as the maximum line length as this seems to be the line length that github can handle.

**Comment by am-kaiser** [comment]
> 
> 
> Ignoring the errors F401 and F403 regarding the "import *" related issues is working now. As this overrides the default .flake from super-linter, a line length error is present now. According to PEP8, the max line length should be 79, but we could set this to a higher value. Looking at compliance-check-lib and cc-yaml, they also seem to allow for longer lines.
> I would propose 119 as the maximum line length as this seems to be the line length that github can handle.

I am fine with increasing the line length to 119.

**Comment by jkretz** [comment]
Okay, I will add this. There are also some errors in the yamls and I will try to fix them.
As this PR has so many commits, we should maybe consider to squash them before the merge.

**Comment by jkretz** [comment]
All linters pass. I furthermore squashed all commits. I think it is ready to merge now.

**Pull request merged**
